# Logitech F710
axis_linear: 1  # Forward/Back > Left Analog Pad
scale_linear: 0.2
#scale_linear_turbo: 0.8

axis_angular: 2  # Rotation > Right Analog Pad
scale_angular: 1.5
#scale_angular_turbo: 2.0

enable_button: 4  # Dead Man button = LB
enable_turbo_button: -1  # Turbo Button disabled because not working properly (Issue Opened on Repo)
